services:
  - type: web
    name: test-read-db-and-summarize-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python run.py
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        value: 10000
      - key: DEBUG
        value: false 